version: '3.9'
services:
    gateway:
        container_name: gateway
        restart: always
        image: lorelor/ayi-docker-gateway:latest
        ports:
            - "7000:7000"
        networks:
            - swapi-net

    characters:
        container_name: characters
        restart: always
        image: lorelor/ayi-docker-characters:latest
        ports:
            - "7001:7001"
        networks:
            - swapi-net

    films:
        container_name: films
        restart: always
        image: lorelor/ayi-docker-films:latest
        ports:
            - "7002:7002"
        networks:
            - swapi-net

    planets:
        container_name: planets
        restart: always
        image: lorelor/ayi-docker-planets:latest
        ports:
            - "7003:7003"
        networks:
            - swapi-net

    db:
        container_name: db
        restart: always
        image: lorelor/ayi-docker-db:latest
        ports:
            - "7004:7004"
        networks:
            - swapi-net

    client:
        container_name: client
        restart: always
        image: lorelor/ayi-docker-client:latest
        ports:
            - "5173:5173"
        networks:
            - swapi-net

networks:
    swapi-net:
        driver: bridge
