apiVersion: v1
kind: Service   
metadata:
  name: {{ .Release.Name }}-characters
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: characters
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: characters
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.characters.service.port }}
      targetPort: {{ .Values.characters.service.port }}
