apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.port }}
      nodePort: {{ .Values.client.service.nodeport }}