apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-planets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: planets
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: planets
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.planets.service.port }}
      targetPort: {{ .Values.planets.service.port }}