apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: swapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      restartPolicy: Always
      containers:
        - name: client
          image: lorelor/ayi-docker-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173