apiVersion: apps/v1
kind: Deployment
metadata:
  name: planets
  namespace: swapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planets
  template:
    metadata:
      labels:
        app: planets
    spec:
      restartPolicy: Always
      containers:
        - name: planets
          image: lorelor/ayi-docker-planets:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7003
          env:
            - name: MONGO_URI
              value: "mongodb://db.swapi2.svc.cluster.local:7004"