apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: swapi
  labels:
    app: gateway
    role: backend
    tier: backend
spec:
  type: NodePort
  selector:
    app: gateway
    role: backend
    tier: backend
  ports:
    - port: 7000
      targetPort: 7000
      nodePort: 30000